Ft article rating #159053987
andela/ah-scorpion pull request #24
Opened 2018-08-09 13:49 UTC by davenjeru

2018-08-10 11:12 UTC, munyili-samuel approved these changes
I have tested the PR and it works as shown on the description.
The tests are also passing.
Good job

2018-08-10 12:31 UTC, kipropbrian commented
Hey Dave, the title of this PR does not follow andela guidelines.

2018-08-11 17:30 UTC, hoslack approved these changes
Great work there

2018-08-11 23:43 UTC, dmigwi commented
Your commit messages is too repetitive. It should be concise and descriptive without any repeated words wherever possible.

<img width="685" alt="screen shot 2018-08-12 at 02 39 06" src="https://user-images.githubusercontent.com/22055953/43997025-3ff3c492-9dd9-11e8-9918-be0ece8d5315.png">

2018-08-13 03:56 UTC, RuthNjeri requested changes

2018-08-13 03:56 UTC, RuthNjeri commented on authors/apps/ratings/tests.py
> +        pass
I do not think `pass` is necessary here.

2018-08-13 06:23 UTC, lennykioko commented on authors/apps/ratings/serializers.py
> +        # If the article is not found the raise error
I think you meant to say **then** and not **the**

2018-08-13 06:33 UTC, lennykioko commented on authors/apps/ratings/urls.py
> +app_name = "articles"
I think that the `app_name` here should be ratings since we are currently in the ratings app.

2018-08-13 07:42 UTC, RuthNjeri commented
The tests work well and the requests return the correct payload.  Good job.

2018-08-13 09:36 UTC, lennykioko approved these changes

2018-08-14 09:05 UTC, RuthNjeri approved these changes

2018-08-14 13:34 UTC, merged