#159053991 Allow Users to Favourite and un Favourite Article
andela/ah-scorpion pull request #26
Opened 2018-08-09 15:25 UTC by munyili-samuel

#### What does this PR do
- Allows users to favourite and unfavourite an article

#### Description of tasks done
- added DB models for favouriting article
- Added urls endpoint for favouriting article
- added views to handle favouriting and un favouriting
- made migrations for database model changes
- added unit tests for this functionality

#### How can this PR be manually tested
Prerequisite: Postman
- use git pull to get the source code from ft-favourite-article-159053991 branch
- use `source .env` to export environmental variables and activate virtual env
- run `python manage.py migrate` to apply recent migrations
- run python manage.py runserver` to start  the project
- if not already done, create a new user account and login
- if not already done, create an article and copy the `slug`
- create a `POST` request to the following endpoint `<str:slug>/favorite/` replacing the `<slug>` with the slug you copied above
- you should get the article back. If you try again you should get a message `You have already marked this article as a favourite`
- create a `DELETE` request to the following endpoint `<str:slug>/favorite/` replacing the `<slug>` with the slug you copied above
- you should get the article back. If you try again you should get a message `You have not marked this article as a favourite`
- if you use a slug that is not valid, you should get a message `The article was not found` on both requests

#### Related PT stories
- [#159053991](https://www.pivotaltracker.com/story/show/159053991)

2018-08-11 17:45 UTC, hoslack approved these changes

2018-08-13 04:25 UTC, RuthNjeri requested changes
Hi Sam,
When I favourite an article using a POST request
```
http://127.0.0.1:8000/api/v1/articles/how-to-train-the-dragon-in-a-ditch-7895168a9cbd41b8ac1822cb729766c0/favorite/
```
 I am getting this as the response 
``` 
{
    "article": {}
}
```
and when unfavourite an article, I get this back
```
{
    "message": {}
}
```
Shouldn't I be getting the article back?

2018-08-13 04:36 UTC, RuthNjeri commented
When I `GET an article` after favoriting it, I get this response
```
    "favorited": [
        2
    ]
```
Is there a reason you have chosen to return the user id of a person who has favorited an article as opposed to their username?

2018-08-13 06:35 UTC, munyili-samuel commented
I will fix this in the next 30min.

> On 13 Aug 2018, at 07:25, Ruth <notifications@github.com> wrote:
> 
> @RuthNjeri requested changes on this pull request.
> 
> Hi Sam,
> When I favourite an article using a POST request
> 
> http://127.0.0.1:8000/api/v1/articles/how-to-train-the-dragon-in-a-ditch-7895168a9cbd41b8ac1822cb729766c0/favorite/
> I am getting this as the response
> 
>     "article": {}
> }
> and when unfavourite an article, I get this back
> 
> {
>     "message": {}
> }
> Shouldn't I be getting the article back?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/andela/ah-scorpion/pull/26#pullrequestreview-145511803>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AnNmshPBZmJJboYD-0c1Pm5jksccmt_hks5uQP-rgaJpZM4V16w2>.
>

2018-08-13 09:38 UTC, davenjeru approved these changes
The PR has been tested and is okay. It has been stated that the end user does not need to know who has favourited an article, they just need to see their favourited articles.

2018-08-13 09:42 UTC, davenjeru commented
It is not a big deal, but who else feels weary about the use of American English on the API endpoints 😅😅😅, Like **favorite** instead of **favourite**. 🤷‍♂️

2018-08-13 10:46 UTC, lennykioko commented on authors/apps/articles/views.py
> +        If already, return message saying that the user has already favourated
Typo: you meant favourited instead of favourated

2018-08-14 09:44 UTC, RuthNjeri approved these changes

2018-08-14 19:50 UTC, dmigwi requested changes
Please fix all the pep8 violations on your PR.

2018-08-15 09:02 UTC, dmigwi commented
How did you end up making 87 commits?

2018-08-15 14:08 UTC, merged