#159053988 Add functionality for users to be able to comment on articles
andela/ah-scorpion pull request #28
Opened 2018-08-12 01:11 UTC by hoslack

**What does this PR do?**
- Allow users to make and delete comments

**Description of tasks completed**
- Create endpoints for CRUD operations of comments
- Create a  model for comments
- Make a column in the comments model for child comments(replies)
- Add unit tests for the comments functionality

**How can this PR be manually tested**
- Git pull the source code from ft-159053988-Comment-on-articles branch
- Copy the variables from `sample.env` and put the correct parameters in `.env` file
- Run `source .env` on your terminal to export environmental variables and activate virtual env
- Run `python manage.py migrate` to apply recent migrations
- Run `pip install -r requirements` to install latest dependencies
- Run `python manage.py runserver` to start the project
- If not already done, create a new user account and login
- Create an article and copy the slug
- Make a POST request to the following endpoint `api/v1/<str: slug>/comments/` replacing the `<slug>` with the slug you copied above. The data should be a comment 
`{"content": "Sample comment"}`
- You should get the comment back. 
- Make a DELETE request to the following endpoint `api/v1/<str: slug>/comments/<int: id>/` replacing the <id> with the id of the comment you got from the delete request you copied above. This returns 204_NO_CONTENT
- Make a GET request with the endpoint `api/v1/<str: slug>/comments/` and view all the comments you have made to the article from which you have taken the slug.

**Relevant Stories**
[159053988](https://www.pivotaltracker.com/n/projects/2184741/stories/159053988)

2018-08-13 07:38 UTC, RuthNjeri commented
The comments work well. Good job!

2018-08-14 07:38 UTC, lennykioko requested changes
I think it would be a good idea if we could allow users to update comments that they have made.

2018-08-14 08:51 UTC, RuthNjeri requested changes

2018-08-14 08:51 UTC, RuthNjeri commented on authors/apps/comments/tests/test_views.py
> +    def test_get_comment_from_article_without_comment(self):
The name of the function and what you have described in the docstrings that the function should do not add up.

2018-08-14 08:51 UTC, RuthNjeri commented on authors/apps/comments/tests/test_views.py
> +
Good job testing extensively.

2018-08-14 08:57 UTC, lennykioko approved these changes

2018-08-14 09:18 UTC, munyili-samuel commented
I have tested and it looks ok to me. Good job

2018-08-14 09:19 UTC, munyili-samuel approved these changes
LGTM

2018-08-14 09:26 UTC, RuthNjeri approved these changes

2018-08-14 13:45 UTC, merged