#160052316 Fix the issues listed on comments and articles endpoints
andela/ah-scorpion pull request #42
Opened 2018-08-27 07:47 UTC by hoslack

**What does this PR do?**
- Fix issues listed in the comment and articles backend

**Description of tasks completed**
- Fix bug that created a slug with "no-title"
- Return 404 if an article with given slug does not exist instead of an empty list

**How can this PR be manually tested**
- Git pull the source code from bug-Fix-Issues-In-The-backend-160052316
- Copy the variables from `sample.env` and put the correct parameters in `.env` file
- Run `source .env` on your terminal to export environmental variables and activate virtual env
- Run `pip install -r requirements` to install latest dependencies
- Run `python manage.py runserver` to start the project
- If not already done, create a new user account and login
- Create an article as shown in the previous instructions
- After creating an article and copy the slug
- Make a POST request to the following endpoint `api/v1/articles/<str: slug>/comments/` replacing the `<slug>` with the slug you copied above. The data should be a comment 
`{"content": "Sample comment"}`
- You should get the comment back. 
- Make a DELETE request to the following endpoint `api/v1/articles/<str: slug>/comments/<int: id>/` replacing the <id> with the id of the comment you got from the delete request you copied above. This returns 204_NO_CONTENT
- Make a GET request with the endpoint `api/v1/articles/<str: slug>/comments/` and view all the comments you have made to the article from which you have taken the slug.
- Make a PATCH request to `api/v1/articles/<str: slug>/` to edit an article even without a new title, the slug should be the same

**Relevant Stories**
[160052316](https://www.pivotaltracker.com/n/projects/2184741/stories/160052316)

2018-09-11 08:43 UTC, davenjeru requested changes
Please fix merge conflicts as soon as possible. The pull request has been open for the longest time.

2018-09-13 03:14 UTC, RuthNjeri requested changes
Hi Hoslack,

Please fix the merge conflicts for the PR to be merged.

2018-09-13 09:11 UTC, lennykioko approved these changes
Nice job

2018-09-13 09:31 UTC, munyili-samuel approved these changes

2018-09-19 08:46 UTC, RuthNjeri approved these changes

2018-09-19 08:47 UTC, davenjeru approved these changes

2018-09-19 09:17 UTC, merged